### ISSUE TITLE
User-scalable=no not working in Samsung Internet v5.4

### ISSUE THREAD

**Issue by katrinaiva** [SamsungInternet/support#12] opened 2017-06-06 10:19 UTC
Hi,
My intention is to prevent user from zooming in or out. The above code isn't working in Samsung Galaxy S6, native browser. Ver 5.4.00-75.

< meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

 Any solution ?

**Comment by katrinaiva** [comment] 2017-06-06 10:21
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
My intention is to prevent user from zooming in or out. The above code isn't working in Samsung Galaxy S6, native browser. Ver 5.4.00-75. Any solution ?

**Comment by poshaughnessy** [comment] 2017-06-15 16:16
Thank you for raising this @katrinaiva and apologies for the slow follow up. I've just checked into this and I've [replicated it too](https://poshaughnessy.github.io/meta-viewport-tests/). I've raised this with colleagues now to check with them and I hope to get back to you ASAP.

**Comment by poshaughnessy** [comment] 2017-09-20 09:41
Replicated in Samsung Internet v6.2 beta too :(

**Comment by pierredewilde** [comment] 2017-10-23 07:01
In Samsung Internet 5.4 and 6.2 Beta, there is a setting to bypass viewport:
```
Settings > Manual zoom
Override website requests to control zoom level.
```

By default, Manual zoom is enabled. Disable it to restore normal viewport behaviour.

**Comment by poshaughnessy** [comment] 2017-11-03 18:02
Thank you very much @pierredewilde, I should have known this!

So it seems like this is 'expected' behaviour after all (although I didn't expect it :))

I will close this issue then, but if you feel that we need to change something to do with this, please continue to comment or add a separate feature request issue, and we can pass on the feedback internally.

**Closed by poshaughnessy** 2017-11-03 18:02 UTC

**Comment by edenprojectde** [comment] 2018-09-28 20:39
How can this be a expected behaviour? No Browser behaves like this, and as a Webdev this ruins the whole symmetry of having a page 100vw. I can zoom out even tough it's not expected. This means i need to adjust the page for every phone to behave right and fight this setting which is really extremly irritating.

**Comment by markoliverbrawn** [comment] 2018-11-08 03:14
Feels like it should be "off" by default, not "on". I think that this phrase says it all: 
> _Disable_ it to restore _normal_ viewport behaviour.

**Comment by edenprojectde** [comment] 2018-11-14 13:53
@poshaughnessy Will this be fixed or will it be ignored?

**Comment by poshaughnessy** [comment] 2018-11-14 21:01
@edenprojectde Sorry I don't work there at Samsung anymore, hopefully one of the team there can help answer if there are any plans to change this.

**Comment by tobiasgraeber** [comment] 2019-01-03 12:47
@poshaughnessy, @torgo, 

Please reopen this issue! Or please provide us any information about who we could send / assign this issue to?!

Zoom is not respected correctly on samsung browser anymore if this is turned on ...
 - As stated before this "feature" should be "off" by default instead "on" and is still not resolved!

At least there should be any explaination about the reasons behind this and / or maybe how you (als a web developer) could force / override this setting or something like that...

Also this is related to #64 

Also it seems this repository is not up to date anymore? So i am going to mail this issue to browser@samsung.com and encourage everybody to to so as well

**Comment by richard-blezer** [comment] 2019-06-19 06:32
I have tested this : 
Chrome browser; Firefox browser >  standard no zooming allowed,
Samsung Internet , Opera > zooming is standard  allowed,
Zooming is a part of the setting for the vision impaired.
